### ISSUE TITLE
Asymmetry can appear in image

### ISSUE THREAD

**Issue by tbronzwaer** [cbrinkerink/webgr#11]
<img width="1052" alt="Screenshot 2019-11-30 20 19 42" src="https://user-images.githubusercontent.com/8244822/69905036-c7782b00-13ae-11ea-9a0a-73fdd40657b8.png">

Happens after flying close to horizon for a while

**Comment by tbronzwaer** [comment]
Idea: continuously print tetradchecks?

**Comment by cbrinkerink** [comment]
I'm trying to picture how a skewed tetrad can impact our camera ray collection. It could lead to our 'sensor plane' (the virtual screen in front of the observer) being effectively angled with respect to the observer position, thus causing a kind of scaling gradient across the image. So, some kind of non-orthogonality of our tetrad vectors may be at play here. Should be easy enough to check.

**Comment by tbronzwaer** [comment]
This may well be fixed now that the 'wobble/precession' is fixed, but not sure. Keep on the lookout for now.

**Comment by tbronzwaer** [comment]
I have subjected the app to some of the most horrific torture I could come up with, flying around the horizon like a madman, but never saw any asymmetry. Marking as closed!
