### ISSUE TITLE
Fix horizon size change discontinuities with changing observer radius

### ISSUE THREAD

**Issue by cbrinkerink** [cbrinkerink/webgr#3]
This has likely to do with the limited resolution of the lookup table. Or an interpolation issue.

**Comment by cbrinkerink** [comment]
If we change the lookup table to cover all look angles that do not end in the BH, along with a list of critical alpha values that describe the apparent horizon angle, we should be able to solve this issue. We will then also get better results close to the horizon, as more look directions are available for mapping.

**Comment by cbrinkerink** [comment]
With a higher-res lookup table (2048x2048), things look a lot better. The ultimate solution to this issue is to implement a variable-alpha-range lookup table. In this table, we use a different alpha limit value for every radius. The lookup table thus only contains valid deflection angles, and never needs to interpolate between valid deflection angles and filler values (when the ray falls into the shadow region).

**Comment by tbronzwaer** [comment]
Agreed, marking as closed for now - a better lookup table is a goal for beyond version 1.0
