### ISSUE TITLE
Update observer position using k_u_obs rather than ad hoc updating

### ISSUE THREAD

**Issue by tbronzwaer** [cbrinkerink/webgr#8]
The following should happen when one of the arrow keys is pressed:

1) translate X_u_obs, k_u_obs and u_u_obs to Cartesian coords
2) take their cross product (call it n)
3) up/down keys: X_u_obs_cart = X_u_obs_cart +/- k_u_obs_cart
4) left/right keys: X_u_obs_cart = X_u_obs_cart +/- n

**Comment by cbrinkerink** [comment]
Implemented. Also: z/x move the observer up/down.
